version: '3.4'

services:
  hfan.web.application:
    image: ${DOCKER_REGISTRY-}hfanwebapplication
    build:
      context: .
      dockerfile: HFan.Web.Application/Dockerfile

  hfan.web:
    image: ${DOCKER_REGISTRY-}hfanweb
    build:
      context: .
      dockerfile: HFAN.Web/Dockerfile
    depends_on:
      - hfan.web.application